fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "hadrien.vinay@yahoo.fr"
        sender_name: "hadrien.vinay@yahoo.fr"
    registration:
        form:
            type: App\Form\UserType
    change_password:
        form:
            type: App\Form\ChangePasswordType