vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images/
            upload_destination: '%kernel.project_dir%/public/build/images/'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
