#index:
#    path: /
#    controller: App\Controller\DefaultController::index

main_app:
    path: /
    controller: App\Controller\MainController::index

timetable:
    path: /timetable
    controller: App\Controller\TimeTableController::timetable

profile:
    path: /profil/{id}
    controller: App\Controller\ProfileController::profil

modify_profile:
    path: /modify/profil/{id}
    controller: App\Controller\ProfileController::modifyProfil

modify_profile_pic:
    path: /modify/profil/pic/{id}
    controller: App\Controller\ProfileController::modifyProfilePicture

calendar:
    path: /calendar
    controller: App\Controller\CalendarController::calendar
    
gallery:
    path: /gallery
    controller: App\Controller\GalleryController::gallery

resume:
    path: /resume
    controller: App\Controller\ResumeController::resume

event:
    path: /event/{id}
    controller: App\Controller\EventController::event

add_event:
    path: /add/event
    controller: App\Controller\EventController::addEvent

modify_event:
    path: /modify/event/{id}
    controller: App\Controller\EventController::modifyEvent

albums:
    path: /albums
    controller: App\Controller\PictureController:showAlbums

album:
  path: /albums/{id}
  controller: App\Controller\PictureController:showAlbum

pictures:
  path: /pictures
  controller: App\Controller\PictureController:showPictures



