main_app:
    path: /
    controller: App\Controller\MainController::index
    
rules:
    path: /rules
    controller: App\Controller\MainController::rules

search:
    path: /search
    controller: App\Controller\MainController:search

autocomplete_search:
    path: /autocomplete
    controller: App\Controller\MainController::autocompleteSearch

#######################
#    Admin routes    #
#######################
admin:
    path: /admin
    controller: App\Controller\AdminController::index
    
change_password:
    path: /admin/changePassword
    controller: App\Controller\AdminController::changePassword
  

#######################
#    Profil routes    #
#######################
profile:
    path: /profil/{id}
    controller: App\Controller\ProfilController::profil

modify_profile:
    path: /modify/profil/{id}
    controller: App\Controller\ProfilController::modifyProfil

add_recommandation:
  path: /add/recommandation
  controller: App\Controller\ProfilController::addRecommandation

add_job:
  path: /add/job
  controller: App\Controller\ProfilController::addJob

fos_user_profile_show:
    path: /profile
    controller: App\Controller\ProfilController::redirectToProfil

#######################
#   Calendar routes   #
#######################
calendar:
    path: /calendar
    controller: App\Controller\CalendarController::calendar
 
news_calendar:
    path: /calendar/news
    controller: App\Controller\CalendarController::newsCalendar
 
#######################
#    Resume routes    #
#######################
resume:
    path: /resume
    controller: App\Controller\ResumeController::resume
    
#######################
#     Media routes    #
#######################
media:
    path: /media
    controller: App\Controller\MediaController::media

add_media:
  path: /add/media
  controller: App\Controller\MediaController::addMedia

delete_media:
    path: /delete/media/{id}
    controller: App\Controller\MediaController:deleteMedia


#######################
#      Map routes     #
#######################
map:
    path: /map
    controller: App\Controller\MapController::map

#######################
#    Event routes     #
#######################
event:
    path: /event/{id}
    controller: App\Controller\EventController::event
    
add_event:
    path: /add/event/{start}/{end}
    controller: App\Controller\EventController::addEvent
    defaults:
        start: 1
        end: 1

modify_event:
    path: /modify/event/{id}
    controller: App\Controller\EventController::modifyEvent
    
add_participant:
    path: /add/participant/{id}
    controller: App\Controller\EventController::addParticipant

cancel_participant:
    path: /cancel/participant/{id}
    controller: App\Controller\EventController::cancelParticipant
    
delete_event:
    path: /delete/event/{id}
    controller: App\Controller\EventController:deleteEvent


#######################
#    Gallery routes   #
#######################
gallery:
    path: /gallery
    controller: App\Controller\GalleryController::gallery

album:
  path: /albums/{id}
  controller: App\Controller\GalleryController:showAlbum
  
add_picture:
  path: /add/picture
  controller: App\Controller\GalleryController:addPicture
  
add_album:
  path: /add/album
  controller: App\Controller\GalleryController:addAlbum
  
delete_album:
  path: /delete/album/{id}
  controller: App\Controller\GalleryController:deleteAlbum
  
delete_picture:
  path: /delete/picture/{id}
  controller: App\Controller\GalleryController:deletePicture
  
#######################
#     Music routes    #
#######################
radio:
    path: /radio
    controller: App\Controller\MusicController::radio

convertor:
    path: /convertor
    controller: App\Controller\MusicController::convertor
    
add_song:
    path: /add/song
    controller: App\Controller\MusicController::addSong

delete_song:
    path: /delete/song/{id}
    controller: App\Controller\MusicController::deleteSong

#######################
#  Dashboard routes   #
#######################
dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::home

timetable:
    path: /timetable
    controller: App\Controller\DashboardController::timetable
  
weather:
    path: /weather
    controller: App\Controller\DashboardController::weather
   
#######################
# Notifications routes#
#######################
mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
        
#######################
#        Catan        #
#######################
catan:
    path: /catan
    controller: App\Controller\CatanController::catan

#######################
#        Space        #
#######################
space:
    path: /space
    controller: App\Controller\SpaceController::space
    
add_space_media:
    path: /add/spaceMedia
    controller: App\Controller\SpaceController::addSpaceMedia
  
update_space_media:
    path: /update/spaceMedia/{id}
    controller: App\Controller\SpaceController::updateSpaceMedia

delete_space_media:
    path: /delete/spaceMedia/{id}
    controller: App\Controller\SpaceController::deleteSpaceMedia


