main_app:
    path: /
    controller: App\Controller\MainController::index
    
rules:
    path: /rules
    controller: App\Controller\MainController::rules
    
autocomplete_search:
    path: /autocomplete
    controller: App\Controller\MainController:autocompleteSearch

#######################
#    Profil routes    #
#######################
profile:
    path: /profil/{id}
    controller: App\Controller\ProfilController::profil

modify_profile:
    path: /modify/profil/{id}
    controller: App\Controller\ProfilController::modifyProfil

modify_profile_pic:
    path: /modify/profil/pic/{id}
    controller: App\Controller\ProfilController::modifyProfilePicture
     
add_recommandation:
  path: /add/recommandation
  controller: App\Controller\ProfilController:addRecommandation

add_job:
  path: /add/job
  controller: App\Controller\ProfilController:addJob

#######################
#   Calendar routes   #
#######################
calendar:
    path: /calendar
    controller: App\Controller\CalendarController::calendar
 
#######################
#    Resume routes    #
#######################
resume:
    path: /resume
    controller: App\Controller\ResumeController::resume

#######################
#      Map routes     #
#######################
map:
    path: /map
    controller: App\Controller\MapController::map

#######################
#    Event routes     #
#######################
event:
    path: /event/{id}
    controller: App\Controller\EventController::event
    
add_event:
    path: /add/event/{start}/{end}
    controller: App\Controller\EventController::addEvent
    defaults:
        start: 1
        end: 1

modify_event:
    path: /modify/event/{id}
    controller: App\Controller\EventController::modifyEvent
    
add_participant:
    path: /add/participant/{id}
    controller: App\Controller\EventController::addParticipant

cancel_participant:
    path: /cancel/participant/{id}
    controller: App\Controller\EventController::cancelParticipant
    
delete_event:
    path: /delete/event/{id}
    controller: App\Controller\EventController:deleteEvent


#######################
#    Gallery routes   #
#######################
gallery:
    path: /gallery
    controller: App\Controller\GalleryController::gallery

album:
  path: /albums/{id}
  controller: App\Controller\GalleryController:showAlbum
  
add_picture:
  path: /add/picture
  controller: App\Controller\GalleryController:addPicture
  
add_album:
  path: /add/album
  controller: App\Controller\GalleryController:addAlbum
  
delete_album:
  path: /delete/album/{id}
  controller: App\Controller\GalleryController:deleteAlbum
  
delete_picture:
  path: /delete/picture/{id}
  controller: App\Controller\GalleryController:deletePicture
  
#######################
#     Music routes    #
#######################
radio:
    path: /radio
    controller: App\Controller\MusicController::radio

convertor:
    path: /convertor
    controller: App\Controller\MusicController::convertor
    
add_song:
    path: /add/song
    controller: App\Controller\MusicController::addSong

delete_song:
    path: /delete/song/{id}
    controller: App\Controller\MusicController::deleteSong

#######################
#  Timetable routes   #
#######################
timetable:
    path: /timetable
    controller: App\Controller\TimeTableController::timetable
   
#######################
# Notifications routes#
#######################
mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
        
#######################
#        Catan        #
#######################
catan:
    path: /catan
    controller: App\Controller\CatanController::catan



