main_app:
    path: /
    controller: App\Controller\MainController::index
    
rules:
    path: /rules
    controller: App\Controller\MainController::rules

#######################
#    Profil routes    #
#######################
profile:
    path: /profil/{id}
    controller: App\Controller\ProfilController::profil

modify_profile:
    path: /modify/profil/{id}
    controller: App\Controller\ProfilController::modifyProfil

modify_profile_pic:
    path: /modify/profil/pic/{id}
    controller: App\Controller\ProfilController::modifyProfilePicture
     
add_recommandation:
  path: /add/recommandation
  controller: App\Controller\ProfilController:addRecommandation

#######################
#   Calendar routes   #
#######################
calendar:
    path: /calendar
    controller: App\Controller\CalendarController::calendar
 
#######################
#    Resume routes    #
#######################
resume:
    path: /resume
    controller: App\Controller\ResumeController::resume

#######################
#      Map routes     #
#######################
map:
    path: /map
    controller: App\Controller\MapController::map
       
map_job:
    path: /map_job
    controller: App\Controller\MapController::mapJob
    
map_event:
    path: /map_event
    controller: App\Controller\MapController::mapEvent

#######################
#    Event routes     #
#######################
event:
    path: /event/{id}
    controller: App\Controller\EventController::event
    
add_event:
    path: /add/event/{start}/{end}
    controller: App\Controller\EventController::addEvent
    defaults:
        start: 1
        end: 1

modify_event:
    path: /modify/event/{id}
    controller: App\Controller\EventController::modifyEvent
    
add_participant:
    path: /add/participant/{id}
    controller: App\Controller\EventController::addParticipant

cancel_participant:
    path: /cancel/participant/{id}
    controller: App\Controller\EventController::cancelParticipant
    
delete_event:
    path: /delete/event/{id}
    controller: App\Controller\EventController:deleteEvent


#######################
#    Gallery routes   #
#######################
gallery:
    path: /gallery
    controller: App\Controller\GalleryController::gallery

albums:
    path: /albums
    controller: App\Controller\GalleryController:showAlbums

album:
  path: /albums/{id}
  controller: App\Controller\GalleryController:showAlbum
  
add_picture:
  path: /add/picture
  controller: App\Controller\GalleryController:addPicture
  
add_album:
  path: /add/album
  controller: App\Controller\GalleryController:addAlbum
  
#######################
#  Timetable routes   #
#######################
timetable:
    path: /timetable
    controller: App\Controller\TimeTableController::timetable
    
mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications



